### ISSUE TITLE
u-root cannot build with go version 1.19, README needs an update

### ISSUE THREAD

**Issue by johnnylinwiwynn** [u-root/u-root#2926]
**Describe the bug**
According to
https://github.com/u-root/u-root?tab=readme-ov-file#usage
with go version 1.19.x , I see the below build error:
 go build
vendor/github.com/u-root/uio/uio/buffer.go:179:18: undefined: binary.NativeEndian
note: module requires Go 1.21

**Additional context**
I can build with an updated go with version 1.21.7, so I suppose the README needs an update for a newer go version.

**Comment by hugelgupf** [comment]
Yeah, it seems we overlooked the readme version. Do you want to send a PR?

**Comment by johnnylinwiwynn** [comment]
Created https://github.com/u-root/u-root/pull/2927

**Comment by hugelgupf** [comment]
Thanks!
